import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <html lang='fa'>
      <body>{children}</body>
    </html>
  )
}